spring:
  config:
    activate:
      on-profile: localdb
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blood-count
    username: qa
    password: qa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        check_nullability: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

app:
  url: http://localhost:4200
  secretKey: 792F423F4428472B4B6250655368566D597133743677397A244326462948404D\