spring:
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: bloodcountapp@gmail.com
    password: cljiwofajhohsgsp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true